### ISSUE TITLE
[FEATURE] Raise "Changed With History" event on variable initialization

### ISSUE THREAD

**Issue by Dino0040** [AdamRamberg/unity-atoms#125]
**Is your feature request related to a problem? Please describe.**
A health bar that is supposed to react differently when health increases or decreases (which is checked by comparing the value pair of the "Changed With History" event) does not receive an initial value. Only after changing the health value when the game is running the event gets raised.

**Describe the solution you'd like**
Raise the "Changed With History" event on Initialization of a variable.

**Describe alternatives you've considered**
Keep code as is and use both a "Changed" event with and without a history where one changes the health bars display value and the other adds an increase / decrease effect separately.

**Comment by iruizmar** [comment]
This was discussed in Discord since it's not clear if it makes sense, semantically speaking, to call neither Changed nor ChangedWithHistory on OnEnable if the value didn't really changed. 

On the other hand, as @Dino0040 said, it's convenient to make those calls in order to be aware of the Atoms's value on OnEnable anywhere just with the reference to the Event. If not, you would need to hold a reference to the AtomVariable itself too.

So @AdamRamberg proposed to have two boolean values, one for Changed event and the other for ChangedWithHistory event, that indicate if they should be invoked or not on the AtomVariable's OnEnable.

**Comment by AdamRamberg** [comment]
Fixed in #126, which is merged to canary. Closing this issue.
