### ISSUE TITLE
[FEATURE] Use one assembly definition file for whole project.

### ISSUE THREAD

**Issue by xvnnnk** [AdamRamberg/unity-atoms#134]
**Is your feature request related to a problem? Please describe.**
When I add Unity Atoms to my project, I have to add reference to 6 or 7 assemblies in my project's assembly definition file. This is so cumbersome specially that you have to reference them one by one in each assembly definition file in your project.

**Describe the solution you'd like**
Only use one assembly definition file for the project.

**Comment by AdamRamberg** [comment]
Hi and thanks for submitting this issue! 

If I get what you are saying, then this is due to that we have split up the project into several packages. Is it possible for you to create an assembly def that points to all your desired Unity Atoms assemblies (let's call it unity-atoms.asmdef), and then in your project's assembly defs point to unity-atoms.asmdef?

**Comment by soraphis** [comment]
I don't think this is possible. 

> I have to add reference to 6 or 7 assemblies in my project's assembly definition file. 

you need to reference `MamboJamboStudios.UnityAtomsBaseAtoms.Runtime` 
also, you need the packages you want.

there is basically no need to reference Core (if you don't want to create custom Atom-Types)
there is no need to reference the `Editor.asmdef` s.

> Is it possible for you to create an assembly def that points to all your desired Unity Atoms assemblies (let's call it unity-atoms.asmdef), and then in your project's assembly defs point to unity-atoms.asmdef?

no, as far as i know its not possible to create a "assembly reference bundle". it is also not enough to reference an assembly that references another. its not transitive.

**Comment by AdamRamberg** [comment]
So if there is no way to make a "assembly reference bundle" then I would say that there is nothing we can do about this, since making it possible would require to restructure the full project and going from a packages based and modular solution to a monolithic approach. I also want to stress what @soraphis wrote above, you don't need to add the Unity Atoms assemblies that are not used. Closing this issue for now. If there is any potential solution that we missed to discuss, please reopen and we can take it from there.
