### ISSUE TITLE
[QUESTION] Keep the changed value in a variable

### ISSUE THREAD

**Issue by xvnnnk** [AdamRamberg/unity-atoms#135]
When you change the value in a variable, it resets into InitialValue after scene stop. How to keep the changed value after exiting play mode?

**Comment by soraphis** [comment]
why would you want that?
if you seek for persistence, you need some kind of serialization system. when building the game, the serializable objects won't keep the state persistant accross playthroughs, so they shouldn't do it in the editor. it's to prevent errors.

**Comment by mnarimani** [comment]
> why would you want that?
> if you seek for persistence, you need some kind of serialization system. when building the game, the serializable objects won't keep the state persistant accross playthroughs, so they shouldn't do it in the editor. it's to prevent errors.

We have an online game and game client receives remote configuration from online server. We are looking to add option to keep the values that server sent for **offline development in Unity Editor**.
With that our designers will connect to server **only once**, after that, they are able to work offline without connecting to server again because values are there.

**Comment by soraphis** [comment]
either:
- generate a config file from the values sent by the server and use that to fill the atoms on the first frame.
- store those settings in a custom ScriptableObject instead of an Atom, they keep their values in the editor. 
- Add a custom menu item to download the config from a server into the atoms while in edito mode

I'm sorry, but changing Atoms such that they don't go back to the initial value would be very counter intuitive in many/all other places.

**Comment by mnarimani** [comment]
> either:
> 
> * generate a config file from the values sent by the server and use that to fill the atoms on the first frame.
> * store those settings in a custom ScriptableObject instead of an Atom, they keep their values in the editor.
> * Add a custom menu item to download the config from a server into the atoms while in edito mode
> 
> I'm sorry, but changing Atoms such that they don't go back to the initial value would be very counter intuitive in many/all other places.

Why not have it as an opt-in feature?

**Comment by soraphis** [comment]
> Why not have it as an opt-in feature?

to prevent missuse? The whole point behind scriptable variables is that they feel like real variables, but can easily be shared.

if you want a plain "unity scriptable object" you can easily create one, if you want to use an atom you can use an atom, the library suggests an architecture/a workflow. 


> If you look at the Original Talk that all of this is based on, you can see that another Variable Scriptable Object is used for resetting the values.

that is the case for the simple Health example. I've used Atoms within game jams with multiple people and you can trust me: resetting to the initial value is a huge benefit when you run your build and bugs start to appear you can't wrap your head around.

it also saves a monobehavior that resets all your variables. it also fixes the problem of handling which monobehavior should handle the reset.


I said it multiple times in discord, but I think it cannot be said enough: UnityAtoms is a tool, use it where it is applicable. you wouldn't use a hammer where you want a saw. Why do you want to cram unity atoms in a place where a simple ScriptableObject would be your best option?

**Comment by mnarimani** [comment]
> Why do you want to cram unity atoms in a place where a simple ScriptableObject would be your best option?
Simple ScriptableObject is not my best option. Scriptable** Object Architecture that was presented in the talk is there to provide an easy way for designers to tweak game variables **and** sharing game state. My use case is the designer-friendly use case, but somehow you insist that this tool should not support it.

**Comment by soraphis** [comment]
I do not suggest, not using Atoms at all, but just **for this single use case**.
Just create a scriptable object, with all variables for your server config. Create an asset from it. success.

it has all properties you want: it keeps the values when leaving play mode. Its references can be shared. I mean ... IT IS a ScriptableObject

what you don't have in a simple SO: change events.

I'm sorry, but **I** cannot see the greater benefit in making reseting the value optional.
**I'd suggest** to make the OnEnable method `protected virtual`, so you can override them in when you need it.

**Comment by AdamRamberg** [comment]
@soraphis I think it is a good idea to make more methods overridable, like `OnEnable`. 

My first reaction to making the reset optional for Variables is that it's not something we would like to do. I agree with @soraphis here that it makes Atoms too cluttered (I believe that it might already be too cluttered) and hard to understand. With that said, I would like to understand your project setup a little bit better. So you have a server where you in editor mode wants to grab values from and then work with those values when working offline. Why can't you set initial value of the Atoms with the values from the server? Could you please describe your setup a little bit more in detail so we can understand your use case better?

**Comment by mnarimani** [comment]
> With that said, I would like to understand your project setup a little bit better. So you have a server where you in editor mode wants to grab values from and then work with those values when working offline. Why can't you set initial value of the Atoms with the values from the server? Could you please describe your setup a little bit more in detail so we can understand your use case better?

Our game is an always online game. So users need to be always online in order to enter the game.
So here is the flow of data in a normal environment (when unity editor is online or game is in production (on device)):
`[Database] -> [Server] -> [Scriptable Objects that hold single values] -> [Game components that need single values (ex. movement speed)]`

Here Unity Atoms are perfectly OK and cover the use case. And variable resetting does not cause 
any problems. (Game can be in runtime so scriptable objects would lose their values anyway).

The use case that Unity Atoms does not support is designer-friendly use-case. Being always online is  a bad requirement for development and testing. Since it slows people down.

So what we decided was that game should be able to work without server connection.
Now the data flow is like this:
`[Scriptable Objects that hold single values] -> [Game components that need single values (ex. movement speed)]`

So now our designers are able to tweak values in variables and see the results right away. 
**But** when they stop the game all the tweaks will be gone and will reset to original values from server. (right?)

Our target workflow that we looking to achieve is that every designer should be able to connect to server once, fetch all the required values to run the game. 
Then every designer can get offline, work on their specific area and tweak variable values, and then when they are happy with what they have in their editor, they can write variables on DB so others can get the updated values when they get online.


P.S: You guys have used Unity Atoms in a couple of games, How did you fine tune the variables?

**Comment by soraphis** [comment]
> But when they stop the game all the tweaks will be gone and will reset to original values from server. (right?)

this is also the case for any other component or object in the scene. unity atoms is even better as InScene objects as it has still stored the latest "Value" in the Value field, just copy the Value to the InitialValue after leaving play mode.

I see how it is a problem for your specific use case, but Atoms behave in a consistent manner to Unity and between release builds and in-editor play mode

**Comment by mnarimani** [comment]
> this is also the case for any other component or object in the scene. unity atoms is even better as InScene objects as it has still stored the latest "Value" in the Value field, just copy the Value to the InitialValue after leaving play mode.
Except that Scriptable Objects are not In Scene game objects. **And "just copy the Value to the InitialValue after leaving play mode." is not acceptable at all**. I don't know why you even mentioned it.

**Comment by soraphis** [comment]
summing it up:

- removing the initialValue reset, does (imho) not fit into the unity and UnityAtoms workflow. 
- making the reset optional is for me a no-go not every feature should be opt-in. especially if the default fits 99% of all use cases (if it would be a 50/50 thing or a 60/40 -> okay make it optional, but like this)
- we should allow more inheritance, to allow users to redefine certain behaviors if they insist to.

@mnarimani alternatives I've presented to you in this thread, from best to worst:
- use a single ScriptableObject for all your server configurational values. tweak those.
   - you may use this SO in a script to fill the values into Atoms
- Create an custom Atom Type where you implement the OnEnable method that it does not reset to initialValue (this works, even if the OnEnable in the parent is not virtual, due to how unity calls those methods)
- copy the Value to InitialValue after leaving play mode...
    - or create a custom editor script, that handles this for you

**Comment by mnarimani** [comment]
But, can you answer this question? You have used this plugin in a couple of games. How do you fine your game variables?
Because what I see, Your plugin design and mindset is completely ignoring this vital feature.

**Comment by AdamRamberg** [comment]
First of all, please keep the conversation civil. No need to be rude to each other (not pointing any fingers, just pointing it out). 

@mnarimani I believe that using Constants instead of Variables would be preferable in your case. Constants are meant to be used for configuration values (eg. walk speed, run speed, initial attack rate, etc). You can set its value in runtime using the `BaseValue` property. There might be a case here for making it ok to set the value via the `Value` property (that is atm throwing if used). Would using Constants suffice for your case?

**Comment by soraphis** [comment]
> But, can you answer this question? You have used this plugin in a couple of games. How do you fine your game variables?
> Because what I see, Your plugin design and mindset is completely ignoring this vital feature.

I use Atoms mostly for the easy cross-scene/cross-gameobject references.
Having health for the player and as UI element, but UI is in another scene? no problem its a FloatVariable now. e.g.

I've had hooked AtomEvents and AtomActions in my own Dialog system (btw. I'm working on an AtomBased Dialog system as package) to trigger state changes and stuff.

I don't use Atoms for GameConfig and Database. In the last project where I used atoms, I used the Unity GameFoundation package for inventory stuff, so fine tuning Item-stats was in there.

As Adam said: When I need a specific start value or stuff like this, I usualy have a AtomConstant with that value. And a script that uses this constant to fill the variable on game start.

@AdamRamberg we could add ImmutableVariableReference deriving from VariableReference, where you can choose between a value and a AtomConstant but not from AtomVariables. 
And use for InitialValue a ImmutableVariableReference.

**Comment by AdamRamberg** [comment]
> @AdamRamberg we could add ImmutableVariableReference deriving from VariableReference, where you can choose between a value and a AtomConstant but not from AtomVariables.
> And use for InitialValue a ImmutableVariableReference.

@soraphis I think this is a good idea for the library, but I don't think however that it will solve the use case for @mnarimani, since it will be hard to reliably call the API to get the values + adding to the Constant / Immutable Ref before OnEnable is called for each Variable.

**Comment by mnarimani** [comment]
I think it's better to just have this "value persistence" behavior in my own fork. 
Can you guide me to points in the code that resets happen/I need to change?

**Comment by AdamRamberg** [comment]
@mnarimani The reason why O'm not 100% convinced to make it possible to opt-out resetting the Variable when entering editor play mode is that Variables are designed for holding a **runtime value**  that could be shared and observed by other scripts in a modular fashion. For example Variables are designed to hold units' health / mana, user's volume settings or the state of an enemy (eg. attacking, chasing, idle). These are values that you want to reset before each time you enter play mode.

Constants on the other hand are designed for holding **configuration and balance** values. These are values that do not change at runtime. Constants could for example hold values like default / initial player health, default / initial unit speed or default / initial attack speed of a unit. 

From my understanding, you want to load values referring to configuration and balance values from the server. Like I mentioned above, even though Constants are not designed to be changed at runtime, it's possible using the `BaseValue` property. If I were you, I would use Constants and then create an editor script that fetches values from the server and then update the local Constants to align with what's on the server side. Let me know if that guides you in the right direction or if there is something that I've missed. 

> I think it's better to just have this "value persistence" behavior in my own fork.
> Can you guide me to points in the code that resets happen/I need to change?

First of all, I would suggest going with the approach above. If you really want to change the behavior of Variables in your fork you would need to change the first couple of rows in `OnEnable` in `AtomVariable.cs`. 

---

Will close this issue for now since I do not believe we will address by doing any code changes to Atoms.
