### ISSUE TITLE
[BUG] Regenerate All Atoms fails

### ISSUE THREAD

**Issue by jrmacgill** [AdamRamberg/unity-atoms#165]
**Describe the bug**
Regenerate All runs but results in errors in the generated code

**To Reproduce**
Tools -> Generate All Atoms

**Expected behavior**
Atoms regenerated with no errors in generated code.

Some classes are missing:
e.g.
AtomBaseVariableEventReferenceUsage
VoidBaseEventReferenceUsage

**Environment**
 - OS: Windows 10
 - Unity Version2019.3.15f1
 - Version of Unity Atoms Master and Canary

**Additional context**

**Comment by AdamRamberg** [comment]
Hi @jrmacgill! 

The "Regenerate all Atoms" functionality is not 100% and there is always some manual work to readjust specifics that have been added to some classes. Haven't come up with really solution for this so far, if you got an idea please let me know. The errors you see are due to that the generator overwrites specifics for some atoms. The only way I know of working with this is to use version control and know what atoms needs manual work (to find out just regenerate all atoms in an untouched project). 

Will be closing the issue, but please reopen if you believe there is a need for further discussions.

**Comment by jmacgill** [comment]
I added nested ifs and per type logic to the template system to fix this.  I'll setup a PR.  Some more cleanup work required but it does generate without modifications needed now.

**Comment by jmacgill** [comment]
Ugh, I clearly need to get better at git.  Sorry the changes got added to my os agnostic path change.  Will sort it them out tomorrow.
