### ISSUE TITLE
[FEATURE] Tutorials improvements

### ISSUE THREAD

**Issue by miikalo** [AdamRamberg/unity-atoms#189]
**Is your feature request related to a problem? Please describe.**
Tutorials are important in driving new user adaptation. The current state of tutorials could use some reworking in structure and content.

**Describe the solution you'd like**
After having a clear starting point with the existing tutorials, I felt abandoned by the tutorials soon after the very basics and was left to my own devices to figure out the features. This can be a huge turn-off to new users and big wins can be made with relatively little effort. Tutorials save the new users time and reduce the risk of misunderstanding a feature and misusing it, then dismissing the feature as unimportant or unhelpful or working around intended, misunderstood functionality somehow.

**Describe alternatives you've considered**
Leave the tutorials on the website be and create a YouTube series of in-depth tutorials.

**Additional context**
Several people in the #help channel in Discord have been asking for variable instancer tutorials.

**Comment by AdamRamberg** [comment]
Thanks for submitting this PR! Really nice work 💪 After my first read through of the changes my biggest concern was where the Mono Hooks section is located combined with the content of that section. It’s assuming that the basic tutorials are right before it. I would suggest moving it to the basic tutorial section or rewriting it so that it’s building on the other intermediate sections. The easiest would probably be to just move it to the basic section. 

Will read through the docs more thoroughly again next chance I get for more detailed feedback.
