### ISSUE TITLE
Refactoring ScriptableObject / Monobehaviour class names

### ISSUE THREAD

**Issue by AdamRamberg** [AdamRamberg/unity-atoms#26]
Not sure if this is related to Unity Atoms or if a solution to this problem should be part of Unity Atoms. Anyway, here we go.. 

It is really annoying that when you rename a MonoBehaviour / ScriptableObject (when using Unity Atoms for example a Game Function or a Game Action) class the reference gets lost and you might need to rewire everything in the editor that used that class. From my understanding Unity is using fileID + a generated guid to reference something hooked up in the editor (or in an asset file). I have also heard that the guid is based on the class name + namespace. So if it is possible to get the generated guid (or if there is an API where you pass class name + namespace), then it would be possible to create a rename script that renames the class + change all the guids in all meta / scene / asset files. The script might be added to the Unity editor or it might be a IDE extension (for example VS Code). Many assumptions here, but if it is possible it would be a great feature.

**Comment by jeffcampbellmakesgames** [comment]
There is an option for something like this for fields where changing the name of a serialized field can result in a loss of the reference/value. In that example the attribute `[FormerlySerializedAsAttribute]` is available and can help preserve older references. See [here](https://blogs.unity3d.com/kr/2015/02/03/renaming-serialized-fields/) for more information on usage.

The problem here though is that its not the reference itself that gets lost, its that the type itself changes when the class is renamed. Unity can't automatically convert from the old to the new type. This isn't likely something that can be solved this way. In general you're much better off settling on a name when first developing.

There are plugins and tools that can make it easier to find broken or missing references though. OdinInspector offers some limited scene validation using their `[NonNull]` attribute on serialized fields and a custom editor window which allows you to verify that a scene isn't missing any references. My AssetValidator tool [here ](https://github.com/jeffcampbellmakesgames/unity-asset-validator) takes this up a notch by allowing you to run validators on your content for the before named functionality as well as a host of others. There are also some widely available menu item scripts that people have iterated on over the years like [this](https://gist.github.com/ProGM/a40acd8ebbb91eb7b2295e65d5eb42c8) that help you to find missing references and such without needing to use a dedicated plugin or tool.

**Comment by AdamRamberg** [comment]
Closing issue due to not being relevant to Unity Atoms.
