### ISSUE TITLE
Create an non generic interface for GameEvent

### ISSUE THREAD

**Issue by AdamRamberg** [AdamRamberg/unity-atoms#51]
In order to subscribe to changes without carrying about the value of the GameEvent.

**Comment by soraphis** [comment]
not sure how that could be archived with an interface.

I've got a branch in my fork, where I implemented some changes. I've added an Event to GameEvent which is parameterless and a refactored GameEvent to be a non-generic base class, here:

https://github.com/soraphis/unity-atoms/blob/proposal/2.0/Source/Core/Events/GameEvent.cs

(I also did some changes to Variables and folder structure, aswell as added a CHANGELOG.md)

**Comment by IceTrooper** [comment]
I checked last 3 commits. It looks nice and clean. It provides a solution for ResetValue, non-generic Variable/Event classes and parametless GameEvents. I think that it would be also good to add GameEvent Listener MonoBehaviour (I don't know how to name it, based on Void Listener, Int Listener, etc.) which could accept all types of GameEvents but could call only parametless methods (it would look almost like Void Listener, but accept all types), just for convention of Listeners.
Waiting for that if @AdamRamberg will accept that or got another idea.

**Comment by IceTrooper** [comment]
Guys @soraphis @AdamRamberg, will you add those changes to the canary branch?

**Comment by soraphis** [comment]
> Guys @soraphis @AdamRamberg, will you add those changes to the canary branch?

i doubt that he will add all those changes together. because I touched quite a few things at once.

if you want to use the changes in the meantime, risking that the API might break in the next update, you can change the package-manager link to:

    "com.mambojambostudios.unity-atoms": "https://github.com/Soraphis/unity-atoms.git#proposal/2.0",

**Comment by AdamRamberg** [comment]
@IceTrooper Sorry for my inactive the last weeks! @soraphis don't have time right now, but will dive into your changes when I get the chance. Question on the project structure: How do you run  the tests or test the editor scripts? From what I can see, the Examples project's manifest is only referencing the Source folder.

**Comment by soraphis** [comment]
@AdamRamberg Not sure if I understand your question.

my git-root is the Asset folder of a unity project. I run the tests in Unity, opening the test runner.. 

I haven't touched the Examples (just renamed them and extracted the tests), they surely need a cleanup too.
there is no need to have a full unity-project-structure inside a ExamplesAndTests folder.
Because the Unity-Project-root is a level above the git project

    Unity-Project
        Assets (git root)
            . . . 
        ProjectSettings....

**Comment by IceTrooper** [comment]
Ok, today it's a day I used your @soraphis fork because I need those features. Could you explain to me how to register a listener to parameterless GameEvent.cs (for now I just used a public OnEvent event in GameEvent.cs)? I think there is a lack of IGameEventListener interface (without < T >). Did you miss that or did you do that in some purpose?

**Comment by IceTrooper** [comment]
Oh, I'm sorry that it's double posting, but...

I also found that it would be good to add parametless GameAction (the same mechanism like for GameEvents, so I think I don't have to describe it more, how it could works).

**Comment by soraphis** [comment]
> Could you explain to me how to register a listener to parameterless GameEvent.cs (for now I just used a public OnEvent event in GameEvent.cs)?

sure. it has been a bit since I looked into the code, but as far as I can tell:

    public class SomeListener : MonoBehaviour{

        [SerializeField] private GameEvent someEvent; // fill in inspector

        void OnEventRaised(){
                // handle the event
        }

        void OnEnable(){ someEvent.OnEvent += OnEventRaised();        }
        void OnDisable(){ someEvent.OnEvent -= OnEventRaised();        }

    }

as an alternative it should be possible to do it like:

        void OnEnable(){ someEventRegister(OnEventRaised);        }
        void OnDisable(){ someEvent.Unregister(OnEventRaised);        }

I'm writing this without an IDE so there might be a syntax error or two

I should note, that the parameterless GameEvent doesn't have the `RegisterListener` method, but only the more flexible `Register(Action)`.
Using this allows it to have a single component handle multiple events with different handle methods.

**Comment by IceTrooper** [comment]
Ok, so I did that like you said before. Could you explain me why didn't you add RegisterListener method?

> that's correct, my changes where made as a proposal to show how it could be done, its by no means complete and be careful when using it: the API may change when/if it is worked into the main project
Yeah, I know, but it's time I have to use something and can't wait for pushing that on master. I like your solution, so I made a fork and now I'm adding some more things.

**Comment by soraphis** [comment]
> Ok, so I did that like you said before. Could you explain me why didn't you add RegisterListener method?

because I think its the more C# way of doing it. it is also more flexible. But one could argue its only personal taste. 

> I like your solution, so I made a fork and now I'm adding some more things.

looked into your fork. Editor should not be inside Source. really. look into other unity packages (from unity-technologies). also if you've a property with public, trivial getter and setter. you could just use a public variable.

**Comment by IceTrooper** [comment]
@soraphis Oh, great you looked at that.

> looked into your fork. Editor should not be inside Source. really. look into other unity packages (from unity-technologies). also if you've a property with public, trivial getter and setter. you could just use a public variable.

I did that only because when I haven't got Editor in Source I didn't have that included in a package, so... I didn't have any of the custom properties and custom editor in my project (isn't the desired effect, is it?). When I moved an Editor directory into Source now I got Editor in a package and all custom editor things went back. So it has to be in the Source when we want a custom editor. Did you check that in your project?
And why do you say that in official packages there aren't any Editor directories, look at TextMeshPro:
![obraz](https://user-images.githubusercontent.com/51023959/63060393-678a7100-bef2-11e9-9f42-8dcb71049d0a.png)

I also got one more problem, so many times I saw that ".\Repos\MyProject\unity-MyProject\Assets\IconAssignmentSettings.json" was modified somehow (I didn't touch that file, what is that file?). I got problems with icons in my project window (in Inspector it went back after I moved Editor directory inside Source). Look at it:
![obraz](https://user-images.githubusercontent.com/51023959/63060312-2eea9780-bef2-11e9-9850-7124f6399036.png)

**Comment by soraphis** [comment]
> I did that only because when I haven't got Editor in Source I didn't have that included in a package, so... I didn't have any of the custom properties and custom editor in my project (isn't the desired effect, is it?).

you're right. "Editor/" has to be listed in the package.json i forgot that. but that isn't a problem of the folder structure

> And why do you say that in official packages there aren't any Editor directories, look at TextMeshPro:

In TextMehsPro there is no "Source", its called "Runtime" and "Editor" and "Runtime" are on the same level, as where our "Editor" and "Source" folder _should_ be

> I also got one more problem, so many times I saw that ".\Repos\MyProject\unity-MyProject\Assets\IconAssignmentSettings.json" was modified somehow (I didn't touch that file, what is that file?).

that's part of Adams icon solution. I can't tell you much about it, sorry.

> I got also problems with icons in my project window (in Inspector it went back after I moved Editor directory inside Source). Look at it:

yeah, i think when i separated it, i also changed some paths'.

> I can't agree at all. I know it's almost the same, but I learned from many articles and good-practices in C# that we should almost always use public properties instead of public fields.

I know all those best practice guides as well, but for unity projects there is no benefit at all. at least i couldn't find one. For game logic code of your specific game there is zero benefit.
Unity recompiles the whole project anyway so you don't have a "your project does not need recompile if the library changes" benefit (which only gives a benefit if you're only changing the field to a property in the first place).
The library (unity-atoms) is not meant to be used with high amount of Reflections. there might be people who do this, but not in that scale and the library itself does not at all.
Databind isn't a thing were interested in either. 
Properties are slower. not that much, but accessing them every frame in hundreds of scripts and targeting mobile platform. just saying.

in the .NET C# world out there, there are valid reasons for properties over variables. especially in library code. but a trivial property in unity code feels wasted to me.

**Comment by AdamRamberg** [comment]
Added none generic base classes to all atoms in commit e732dad66a4002f955a5319c739e895d65429e53. Closing the issue. If I've missed / overlooked something please create a new issue.
