### ISSUE TITLE
Add an AtomInstancer component

### ISSUE THREAD

**Issue by IceTrooper** [AdamRamberg/unity-atoms#53]
![obraz](https://user-images.githubusercontent.com/51023959/63531648-42f15300-c509-11e9-9750-878ffcc9bd47.png)
http://www.roboryantron.com/2017/10/unite-2017-game-architecture-with.html?showComment=1518505684655#c499355616768136746

What do you think about that? Do we need that? It's based on Unite 2017 talk.

**Comment by AdamRamberg** [comment]
@IceTrooper This is pretty interesting. 

Another way to go about this is to create new instances of the SO in `OnEnable`without an instancer. The only functional difference really would be that you can't reuse the Variable as a template in several places, but not sure there is a real use case for this. However, using an instancer will make a script using it more game designer friendly. I'll say that we should implement this into atoms. If you are up to it would be much appreciated with a PR.

**Comment by AdamRamberg** [comment]
**My thoughts on this**
I would like the API to look like like this: 
```
var myIntVariable = GetComponent<AtomInstancer>().Get<IntVariable>(key: "my_key");
```
**Behaviour:**
The AtomInstancer (`MonoBehaviour`) will have a Dictionary / Map of Atoms, containing a Key (string) and a Value (an Atom of any kind). The `Get<T>(string key = null)` method will first try to locate an Atom of type T (T will have the constrain `where T : BaseAtom`). If `key` is omitted it will just pick the first it finds of type `T`, otherwise it does a match on the `key` value. If it finds a match it returns the Atom, otherwise it return `null`.

I would be really appreciate someone making a PR on this. Should not be too much work to get a first version up. Make sure to read the [guidelines](https://github.com/AdamRamberg/unity-atoms/blob/canary/CONTRIBUTING.md) before starting + assign yourself (or ask me) to the issue.

**Comment by AdamRamberg** [comment]
Added in #110
