### ISSUE TITLE
Add Variables directly to Event Listeners

### ISSUE THREAD

**Issue by mutmedia** [AdamRamberg/unity-atoms#66]
It's a bit annoying to have to create events all the time to be able to use the event listeners, so sometimes it would be nice to be able to set either a Variable or an Event to the listener (making the event be used in case it exists, or created on load in case it's not).

**Comment by AdamRamberg** [comment]
Thanks for submitting the issue. I really like this idea! However, I don't think auto creating an event if it doesn't exist is a good idea, since it might not preferable in all cases. 

**My take on this feature:** 

**Is your feature request related to a problem? Please describe.**
Better DX. See comment above by @mutmedia

_This is only applicable for Listeners listening to one type._ 

**Describe the solution you'd like**
Create a new member property in the `AtomListener` class for a Variable of the same type as the current `Event`. Make a PropertyDrawer for the Event / Variable pair OR make a custom Editor for the `AtomListener`. The Editor / PropertyDrawer should be similar to the PropertyDrawer for References, eg. choose Event or Variable in a "Popup" (`Event` by default) and then corresponding PropertyField. 

**Describe alternatives you've considered**
Not creating a custom PropertyDrawer. However, I think it's preferable to do so. 

**Additional note**
Use `UnityEngine.UIElements` when developing the Editor / PropertyDrawer. All new Editor development should be done using the new UIElements since that is the direction that Unity is going. 

I would really appreciate a PR for this. Read the [contribution guidelines](https://github.com/AdamRamberg/unity-atoms/blob/canary/CONTRIBUTING.md) before starting.

**Comment by AdamRamberg** [comment]
Fixed in #111 - You can now use AtomEventReference for this.
