### ISSUE TITLE
Efficient AtomicTags

### ISSUE THREAD

**Issue by soraphis** [AdamRamberg/unity-atoms#8]
I just saw the atomittacs issue/feature and it has imho many of the problems unity has with its own tags:

https://github.com/AdamRamberg/unity-atoms/blob/v1.0.0/Assets/UnityAtoms/AtomicTags/AtomicTags.cs

checking if a tag is in the list: O(n) in a hashset O(1). now, hashsets are not serializable but: [ISerializationCallbackReceiver](https://docs.unity3d.com/ScriptReference/ISerializationCallbackReceiver.html) to the rescue.

also, tagged objects could add/remove themselfs (OnEnable / OnDisable) from a `static Dictionary<StringReference, List<GameObject>>` with the addition of `public static GameObject[] FindByAtmicTag(...)`

unity has for its own tags a list of all tagged objects and iterates through all of them, IIRC.

also make AtomicTags a [ListComponent](https://garry.tv/2015/06/14/unity-tips/) or something similar... maybe: `static Dictionary<GameObject, AtomicTags>` this could help further down below on HasTag
_________________

for the [extension methods](https://github.com/AdamRamberg/unity-atoms/blob/dfd70a8944acbeabe5feba1cf6cff2be6802c470/Assets/UnityAtoms/Extensions/GameObjectExtensions.cs)

they all scream inefficient. GetTags calls GetComponentTwice -> could cache it
(same for HasTag)

HasTag could become:

    var tags = AtomicTags.GetForGameObject(go); // uses the static Dictionary<GameObject, AtomicTags>
    return tags != null ? tags.Contains(str) : false; 

**note:** also overload hashCode from StringConstant to be equal to its `Value` member. maybe do it for all in the base class ScriptableVariable base, can't think of any drawback for now.

Equivalently GetTag could become:

    var tags = AtomicTags.GetForGameObject(go);
    return tags != null ? tags.GetTags() : new List<StringConstant>(0);

**Comment by AdamRamberg** [comment]
@soraphis Thanks for some good points and suggestions! ❤️ 

I will try to break down the stuff that you bring up, let me know if I've missed something. 

**Change from List to Hashset in AtomicTags.cs**
My reasoning for putting it in a List instead of a HashSet has been that it would be too much work, for little pay off. Often the tags would just be a maximum of 3 items (in my cases), so the performance win would insignificant. Been doing some stuff with the [ISerializationCallbackReceiver](https://docs.unity3d.com/ScriptReference/ISerializationCallbackReceiver.html) and it can be very tricky. Also think that `AtomicTags.GetForGameObject` (see below) would be easier with just using a List (no garbage when converting to a different container). However, this is very doable. Do you have any cases where you would like to tag a GameObject with a lot of tags? Or could you elaborate more on the benefits? 

**public static GameObject[] FindByAtomicTag(...)**
I really like this idea! 2 things though, I think the Dictionary should store strings as keys rather than StringConstants (don't see a point of storing the constants here). I also think that FindByAtomicTag should return a List<GameObject> instead of a GameObject[], we are already storing the GameObjects in a List (meaning that converting it to a regular array would create garbage every time) and a List is much easier to work with for the consumer. Do you agree? If you do I will create an issue and I would gladly accept a pull request (or I will dig into it when I have time). 

**Cache GetComponent in extension methods**
This is a great point! Just created [this](https://github.com/AdamRamberg/unity-atoms/issues/9) issue, feel free to contribute :) 

** ListComponent **
Don't see the advantage using a ListComponent over just having a regular component. What are the advantages that you see? 

**AtomicTags.GetForGameObject(go)**
Even though I'm skeptical towards the ListComponent solution I think that 
`public static List<string> AtomicTags.GetAtomicTags(GameObject go)` is a sound idea.
Created [issue](https://github.com/AdamRamberg/unity-atoms/issues/10).

**Overload hashCode for ScriptableVariable**
Sounds like a great idea! Created [this issue](https://github.com/AdamRamberg/unity-atoms/issues/11).

**Comment by soraphis** [comment]
> I also think that FindByAtomicTag should return a List instead of a GameObject[],

I intentionally made it an array for two reasons: 1. Its the same for other Unity FindBy... methods, they return arrays. 2. you don't want to return a reference to your list, because it could be mutated, so you'd at least return a copy (or use an ImmutableList).    
Also: as for any "Find" method, they should not be called every frame, even if they are efficient as possible.

**ListComponent**

you always, have a reference over all your (active) AtomicTag Components. it is the basis for the efficiency of `FindByAtomicTag`.
